import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { Card, CardHeader } from "@/components/Card";
import { DashboardShell } from "@/components/PageShell";
import { formatCNY } from "@/lib/format-currency";
import { servicePricing } from "@/lib/service-pricing";

const rows = [
  ["学校要求整理", true, true, true], ["材料清单", true, true, true], ["字段填写辅助", true, true, true], ["用户自行填写系统", true, false, false], ["Atlas 填写系统", false, true, true], ["Atlas 正式递交", false, true, true], ["多校统一管理", "基础", "按学校购买", true], ["Offer 跟踪", "基础状态", true, true], ["Campus France", false, false, "法国套餐包含"], ["签证支持", false, false, "按套餐规则"],
] as const;

export default function ServiceComparisonPage() {
  return <DashboardShell><div className="space-y-6 pb-16"><header><p className="text-xs uppercase tracking-[0.28em] text-[#9a8b7c]">申请方式</p><h1 className="mt-2 font-editorial text-5xl font-semibold text-[#2f2924] md:text-6xl">申请方案对比</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#6f6256]">完整申请规划免费开放。你可以自己准备，也可以按学校购买递交服务或查看全流程方案。</p></header><Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-[#f7f0e8] text-[#2f2924]"><tr><th className="p-4 font-medium">服务内容</th><th className="p-4 font-medium">自助申请</th><th className="p-4 font-medium">单校递交</th><th className="p-4 font-medium">全流程申请</th></tr></thead><tbody>{rows.map(([label, self, single, full]) => <tr key={label} className="border-t border-[#e8dfd3]"><td className="p-4 text-[#4a3d34]">{label}</td>{[self, single, full].map((value, index) => <td key={index} className="p-4 text-[#6f6256]">{value === true ? <Check size={17} className="text-[#5f805f]" /> : value === false ? "—" : value}</td>)}</tr>)}</tbody></table></div></Card><div className="grid gap-4 lg:grid-cols-3"><Plan title="自助申请" price="免费" description="自己在学校官网完成递交，Atlas 提供材料与填写辅助。" href="/applications" label="开始自助申请" /><Plan title="单校申请递交" price={`${formatCNY(servicePricing.singleSchoolSubmission)}／学校`} description="Atlas 根据你确认的信息填写，最终提交前由你确认。" href="/dashboard/order-application?service=single-school" label="选择单校递交" dark /><Plan title="全流程申请" price={`英国／澳洲 ${formatCNY(1999)} · 法国 ${formatCNY(5999)}`} description="查看国家套餐、人工服务边界和后续服务计划。" href="/dashboard/order-application?service=full-service" label="查看全流程服务" /></div><Card><CardHeader title="附加服务" /><div className="grid gap-3 md:grid-cols-2"><Plan title="一对一留学规划咨询" price={`${formatCNY(servicePricing.advisorConsultation)}／次`} description="人工复核背景、方向和申请优先级。" href="/dashboard/order-application?service=consultation" label="预约一对一规划" /><Plan title="专业文书服务" price={`${formatCNY(500)}／份`} description="专业文书服务独立计费，不包含在申请方案内。" href="/dashboard/order-application?service=essay" label="购买文书服务" /></div></Card></div></DashboardShell>;
}

function Plan({ title, price, description, href, label, dark = false }: { title: string; price: string; description: string; href: string; label: string; dark?: boolean }) { return <div className={`rounded-2xl border p-5 ${dark ? "border-[#2f2924] bg-[#2f2924] text-[#fffaf3]" : "border-[#e8dfd3] bg-[#fffaf3]"}`}><p className="text-sm opacity-70">{title}</p><p className="mt-2 text-2xl font-semibold">{price}</p><p className="mt-3 min-h-12 text-sm leading-6 opacity-80">{description}</p><Link href={href} className={`mt-4 inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm font-medium ${dark ? "bg-[#fffaf3] text-[#2f2924]" : "border border-[#d8ccbe] text-[#2f2924]"}`}>{label}<ArrowRight size={15} /></Link></div>; }
