"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, CalendarDays, CheckCircle2, FileCheck2 } from "lucide-react";
import { Card } from "@/components/Card";
import { DashboardShell } from "@/components/PageShell";
import { applicationProfile, applicationStateCopy, ApplicationHomeState, ApplicationRecord, getApplicationServiceRecommendation, recommendations } from "@/lib/application-prototype-data";
import { isApplicationWorkspacePurchased, readApplicationRecords, readApplicationSelection } from "@/lib/application-store";
import { getAtlasPrimaryTask } from "@/lib/atlas-task-selector";
import { DevelopmentJourneyRepository } from "@/lib/visual-prototype-data";

export function ApplicationHomeClient() {
  const [records] = useState<ApplicationRecord[]>(() => readApplicationRecords());
  const [selectedIds] = useState<string[]>(() => readApplicationSelection());
  const [workspacePurchased] = useState(() => isApplicationWorkspacePurchased());
  const selected = records.length ? records.map((record) => recommendations.find((school) => school.id === record.schoolRecommendationId)).filter(Boolean) as typeof recommendations : recommendations.filter((school) => selectedIds.includes(school.id) || (!selectedIds.length && school.isSelected));
  const primaryTask = getAtlasPrimaryTask({ applicationRecords: records, selectedSchoolIds: selectedIds, workspacePurchased, journeyNodes: DevelopmentJourneyRepository.getNodes() });
  const state: ApplicationHomeState = records.length ? "school_confirmed" : "report_ready";
  const copy = applicationStateCopy[state];
  const awaitingWorkspace = primaryTask.id === "choose-application-service";
  const service = getApplicationServiceRecommendation({ confirmedApplications: records, purchasedServices: false, consultationPurchased: applicationProfile.consultationPurchased });

  return <DashboardShell><div className="space-y-6">
    <header><p className="text-xs uppercase tracking-[0.28em] text-[#9a8b7c]">申请规划</p><h1 className="mt-2 font-editorial text-5xl font-semibold text-[#2f2924] md:text-6xl">我的申请</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#6f6256]">Atlas 把学校确认、材料准备和正式申请安排在同一条清晰路径上。</p></header>
    <Card className="p-5 md:p-7"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-xs uppercase tracking-[0.24em] text-[#9a8b7c]">申请计划概览</p><h2 className="mt-3 font-editorial text-4xl font-semibold text-[#2f2924]">{applicationProfile.intake}入学</h2><div className="mt-5 grid gap-4 text-sm text-[#5d5148] sm:grid-cols-3"><Info label="目标国家" value={applicationProfile.targetCountries.join("、")} /><Info label="目标方向" value={applicationProfile.targetSubjects.join("、")} /><Info label="计划申请" value="4–6 所学校" /></div></div><Link href="/applications/recommendations" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#2f2924] px-5 py-3 text-sm font-medium text-[#fffaf3]">查看推荐学校 <ArrowRight size={16} /></Link></div></Card>
    <Card className="border-2 border-[#2f2924] p-5 md:p-7"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><p className="text-xs uppercase tracking-[0.24em] text-[#9a8b7c]">当前最需要完成</p><h2 className="mt-3 font-editorial text-4xl font-semibold text-[#2f2924]">{primaryTask.title}</h2><p className="mt-3 max-w-2xl text-base leading-7 text-[#5d5148]">{primaryTask.description}</p></div><span className="rounded-full border border-[#c9dbc5] bg-[#e7ece7] px-3 py-1 text-xs font-medium text-[#4f6d54]">{awaitingWorkspace ? "等待开通" : "现在可以处理"}</span></div><div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-[#f7f0e8] p-4"><p className="text-xs uppercase tracking-[0.18em] text-[#9a8b7c]">Atlas 已准备</p><ul className="mt-3 space-y-2 text-sm text-[#4a3d34]">{(primaryTask.atlasPreparedItems ?? copy.prepared).map((item) => <li key={item} className="flex gap-2"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-[#6f856a]" />{item}</li>)}</ul></div><div className="rounded-2xl bg-[#fffaf3] p-4"><p className="text-xs uppercase tracking-[0.18em] text-[#9a8b7c]">下一步</p><p className="mt-3 text-sm leading-6 text-[#4a3d34]">{awaitingWorkspace ? "开通后即可进入学校录取要求和申请材料页面。" : records.length ? "进入第一所学校的材料准备页面。" : "免费查看完整推荐学校并确认申请名单。"}</p><Link href={records.length ? primaryTask.actionHref : "/applications/recommendations"} className="mt-4 inline-flex items-center gap-2 text-sm font-medium text-[#2f2924] underline decoration-[#c8a96b] underline-offset-4">{primaryTask.actionLabel} <ArrowRight size={15} /></Link></div></div></Card>
    <section><div className="mb-4"><p className="text-xs uppercase tracking-[0.24em] text-[#9a8b7c]">已确认的申请学校</p><h2 className="mt-2 font-editorial text-3xl font-semibold text-[#2f2924]">我的申请学校</h2></div><div className="grid gap-4 md:grid-cols-2">{selected.map((school) => <SelectedSchool key={school.id} school={school} confirmed={records.length > 0} />)}</div></section>
    <ServiceRecommendation service={service} hasConfirmed={records.length > 0} />
    <section><div className="mb-4"><p className="text-xs uppercase tracking-[0.24em] text-[#9a8b7c]">Atlas 已完成的准备</p><h2 className="mt-2 font-editorial text-3xl font-semibold text-[#2f2924]">Atlas 已为你准备</h2></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{["已筛选 8 所学校", "已整理学校申请要求", "已生成申请时间安排", "已标记可复用材料", "已准备个人陈述写作重点"].map((item) => <div key={item} className="rounded-2xl bg-[#f7f0e8] p-4 text-sm text-[#4a3d34]"><FileCheck2 size={17} className="text-[#8ea08b]" /><p className="mt-3">{item}</p></div>)}</div></section>
    <section className="border-t border-[#e8dfd3] pt-5"><div className="flex items-center gap-2"><CalendarDays size={17} className="text-[#8ea08b]" /><h2 className="text-sm font-semibold text-[#2f2924]">近期重要日期</h2></div><div className="mt-3 grid gap-2 text-sm text-[#5d5148] md:grid-cols-3"><DateItem date="7 月 18 日" label="Atlas 建议完成：确认学校名单" /><DateItem date="7 月 20 日" label="Atlas 建议完成：材料检查" /><DateItem date="2027 年 1 月 31 日" label="官方截止日期：University of Leeds" /></div></section>
  </div></DashboardShell>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-[#9a8b7c]">{label}</p><p className="mt-1 font-medium text-[#2f2924]">{value}</p></div>; }
function DateItem({ date, label }: { date: string; label: string }) { return <div className="rounded-2xl bg-[#f7f0e8] p-4"><p className="font-semibold text-[#2f2924]">{date}</p><p className="mt-1 leading-6">{label}</p></div>; }
function SelectedSchool({ school, confirmed }: { school: (typeof recommendations)[number]; confirmed: boolean }) { return <Card className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-[#8f847a]">{school.country} · {school.city}</p><h3 className="mt-1 text-lg font-semibold text-[#2f2924]">{school.universityName}</h3><p className="mt-1 text-sm text-[#6f6256]">{school.programName}</p></div><span className="rounded-full border border-[#c9dbc5] bg-[#e7ece7] px-3 py-1 text-xs text-[#4f6d54]">{confirmed ? "已确认申请" : "已选择"}</span></div><p className="mt-5 text-sm text-[#5d5148]">材料已检测到 {school.materialsReady}/{school.materialsTotal} 项</p>{confirmed ? <Link href={`/applications/app-${school.id}/materials`} className="mt-4 inline-flex text-sm font-medium text-[#2f2924] underline underline-offset-4">开始准备材料 <ArrowRight size={15} /></Link> : null}</Card>; }
function ServiceRecommendation({ service, hasConfirmed }: { service: ReturnType<typeof getApplicationServiceRecommendation>; hasConfirmed: boolean }) { if (!hasConfirmed) return null; return <Card className="p-5 md:p-6"><p className="text-xs uppercase tracking-[0.24em] text-[#9a8b7c]">申请方式</p><div className="mt-2 flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><h2 className="font-editorial text-3xl font-semibold text-[#2f2924]">{service.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#6f6256]">{service.description}</p></div><Link href={service.href} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full border border-[#2f2924] px-5 py-3 text-sm font-medium text-[#2f2924]">{service.cta} <ArrowRight size={15} /></Link></div><div className="mt-4 flex flex-wrap gap-2">{service.details.map((item) => <span key={item} className="rounded-full bg-[#f7f0e8] px-3 py-2 text-xs text-[#5d5148]">{item}</span>)}</div></Card>; }
