import type { SchoolRecommendation } from "../application-prototype-data"; import type { StudentProfile } from "../student-profile"; import { expandField,relationAllowed } from "./field-expansion"; import { assessEligibility } from "./eligibility"; import { OfficialWebDiscoveryProvider,type ProgrammeDiscoveryProvider } from "./programme-discovery"; import { understandProfile } from "./profile-understanding"; import { verifyOfficialProgramme } from "./official-verification"; import type { DiscoveredProgramme,OrchestratorEvent,OrchestratorResult } from "./types";
const event=(stage:OrchestratorEvent["stage"],label:string,status:OrchestratorEvent["status"],detail?:string):OrchestratorEvent=>({stage,label,status,detail});
export async function orchestrateRecommendations(input:{profile:StudentProfile;internalProgrammes?:SchoolRecommendation[];plannedApplicationCount?:number;discoveryProvider?:ProgrammeDiscoveryProvider}):Promise<OrchestratorResult>{
 const events:OrchestratorEvent[]=[]; const profile=understandProfile(input.profile,input.plannedApplicationCount);events.push(event("profile_understanding","已理解学生背景","completed",profile.educationCountry==="英国"?"英国本科按国际/英国学历规则评估，不使用中国院校规则。":undefined));
 const expansions=expandField(profile.targetField);events.push(event("field_expansion","已完成专业语义扩展","completed",`${expansions.length} 个多语言检索词`));
 const internal:DiscoveredProgramme[]=(input.internalProgrammes??[]).filter(p=>profile.targetCountries.includes(p.country)).map(p=>({institution:p.universityName,programme:p.programName,officialUrl:p.officialProgramUrl??"",fieldRelation:"adjacent" as const,discoveryQuery:"internal",discoveredAt:new Date().toISOString()})).filter(p=>p.officialUrl);events.push(event("internal_search","已检索内部数据库","completed",`${internal.length} 个正式候选`));
 const niche=expansions.length>=8; const countryCoverageLow=profile.targetCountries.some(x=>["法国","France"].includes(x))&&internal.length<profile.plannedApplicationCount; const trigger=internal.length<profile.plannedApplicationCount||internal.length/Math.max(profile.plannedApplicationCount,1)<.75||niche||countryCoverageLow;
 let discovered:DiscoveredProgramme[]=[];let passes=0;const provider=input.discoveryProvider??new OfficialWebDiscoveryProvider(); if(trigger){events.push(event("programme_discovery","正在检索相关项目","running"));discovered=await provider.discover(profile,expansions,Math.max(profile.plannedApplicationCount*3,12));passes++;events.push(event("programme_discovery","已完成外部官方项目发现","completed",`${discovered.length} 个候选`))}
 let pool=[...internal,...discovered].filter((p,i,a)=>relationAllowed(p.fieldRelation,profile.crossDisciplinePreference)&&a.findIndex(x=>x.officialUrl===p.officialUrl)===i);events.push(event("official_verification","正在核验官方录取要求","running")); let verified=await Promise.all(pool.map(verifyOfficialProgramme));events.push(event("official_verification","已完成首轮官方核验","completed",`${verified.length} 个项目`));
 let candidates=verified.map(p=>assessEligibility(profile,p)); const issues:string[]=[]; if(candidates.length<profile.plannedApplicationCount)issues.push("推荐数量不足"); if(!profile.targetCountries.length)issues.push("目标国家未提供"); if(expansions.length<2)issues.push("专业同义词覆盖不足"); if(candidates.some(x=>x.verificationStatus!=="verified"))issues.push("存在待核验信息"); if(candidates.some(x=>x.recommendationBand==="currently_not_suitable"&&!Object.values({a:x.academicStatus,l:x.languageStatus,b:x.budgetStatus,t:x.timelineStatus}).includes("does_not_meet")))issues.push("未知被错误判断为不符合");
 if(candidates.length<profile.plannedApplicationCount&&passes<2){events.push(event("supervisor","Supervisor 要求扩大检索","running","首轮候选不足"));const more=await provider.discover(profile,expansions,profile.plannedApplicationCount*5);passes++;pool=[...pool,...more].filter((p,i,a)=>relationAllowed(p.fieldRelation,profile.crossDisciplinePreference)&&a.findIndex(x=>x.officialUrl===p.officialUrl)===i);verified=await Promise.all(pool.map(verifyOfficialProgramme));candidates=verified.map(p=>assessEligibility(profile,p));}
 candidates.sort((a,b)=>a.recommendationBand==="currently_not_suitable"?1:b.recommendationBand==="currently_not_suitable"?-1:b.score-a.score);events.push(event("ranking","已完成核验的推荐","completed",`${candidates.length} 个项目`));events.push(event("supervisor","Supervisor 已完成结果检查","completed"));events.push(event("complete","推荐流程完成","completed"));return{profile,expansions,candidates,events,supervisor:{sufficient:candidates.length>=profile.plannedApplicationCount,issues,discoveryPasses:passes}};
}



