import assert from "node:assert/strict";
import test from "node:test";
import { normalizeStudentProfile } from "../student-profile";
import { expandField } from "./field-expansion";
import { understandProfile } from "./profile-understanding";
import { retrieveCachedVerifiedProgrammes } from "./programme-repository";
import { orchestrateRecommendations } from "./orchestrator";
function cached(countries: string[], subject: string) { const profile = normalizeStudentProfile({ targetCountries: countries, targetSubjects: [subject], targetDegreeLevel: "硕士" }); const understood = understandProfile(profile); return retrieveCachedVerifiedProgrammes(understood, expandField(understood.targetField)); }
function assertSafeResults(results: ReturnType<typeof cached>, countries: string[]) { assert.ok(results.length > 0); for (const item of results) { assert.ok(countries.includes(item.country)); assert.notEqual(item.institutionName.trim().toLowerCase(), item.programmeName.trim().toLowerCase()); assert.ok(!/(book|article|shop|marketplace|navigation|visa|materials)/i.test(item.institutionName)); assert.ok(!/(book|article|shop|marketplace|navigation)/i.test(item.programmeName)); } }
test("protected fixed scenarios return only safe official programmes", () => { assertSafeResults(cached(["法国", "英国"], "International Business"), ["法国", "英国"]); assertSafeResults(cached(["法国", "英国"], "艺术管理"), ["法国", "英国"]); assertSafeResults(cached(["法国"], "法学"), ["法国"]); });
test("missing language scores do not erase recommendation results", () => assertSafeResults(cached(["法国", "英国"], "International Business"), ["法国", "英国"]));
test("OpenAI failure returns verified cache or a structured empty result", async () => { const profile = normalizeStudentProfile({ targetCountries: ["法国"], targetSubjects: ["法学"], targetDegreeLevel: "硕士", languageTests: [] }); const result = await orchestrateRecommendations({ profile, aiProvider: { generate: async () => { throw Object.assign(new Error("mock unavailable"), { status: 503 }); } }, discoveryProvider: { discover: async () => [] } }); assert.equal(result.aiStatus, "unavailable"); assert.ok(result.candidates.length > 0 || (result.generationStatus === "empty" && Boolean(result.aiErrorCode || result.emptyReason))); });
test("arbitrary UK subject is accepted by semantic mock without taxonomy hard-coding", async () => { const profile = normalizeStudentProfile({ targetCountries: ["英国"], targetSubjects: ["Quantum Heritage Informatics"], targetDegreeLevel: "硕士" }); const result = await orchestrateRecommendations({ profile, aiProvider: { generate: async () => [{ schoolName: "Example University", schoolNameLocal: null, programName: "MSc Quantum Heritage Informatics", programNameLocal: null, country: "UK", city: null, degreeLevel: "master", subjectArea: "Quantum Heritage Informatics", category: "target", estimatedFitScore: 75, recommendationReasons: [], applicantStrengths: [], admissionConcerns: [], admissionRequirements: [], missingRequirements: [], verificationQueries: [], expectedOfficialDomain: "example.ac.uk", possibleOfficialUrl: null, confidence: 0.8 }], assessSubjectRelevance: async () => [{ index: 0, relevant: true, relation: "synonym", reason: "fixed semantic mock" }] }, discoveryProvider: { discover: async () => [] } }); assert.equal(result.debug.pendingVerification, 1); assert.ok(result.reviewQueue.some((item) => item.lead.searchTitle.includes("Quantum Heritage Informatics"))); });
