"use client";

import Link from "next/link";
import { useSyncExternalStore } from "react";
import { ArrowRight, CalendarDays, CheckCircle2, FileCheck2 } from "lucide-react";
import { Card } from "@/components/Card";
import { DashboardShell } from "@/components/PageShell";
import { applicationStateCopy, ApplicationHomeState, ApplicationRecord, getApplicationServiceRecommendation, recommendations } from "@/lib/application-prototype-data";
import { getApplicationStateSnapshot, getServerApplicationStateSnapshot, readApplicationSelection, ServiceOrder, subscribeToApplicationState } from "@/lib/application-store";
import { readActivePlanningRun, readPlanningRun } from "@/lib/planning-store";
import { getAtlasPrimaryTask } from "@/lib/atlas-task-selector";

export function ApplicationHomeClient({ runId: requestedRunId }: { runId?: string }) {
  const snapshot = useSyncExternalStore(subscribeToApplicationState, getApplicationStateSnapshot, getServerApplicationStateSnapshot);
  const applicationState = snapshot === "server" ? { records: [] as ApplicationRecord[], selection: [] as string[], workspacePurchased: false, orders: [] as ServiceOrder[] } : JSON.parse(snapshot) as { records: ApplicationRecord[]; selection: string[]; workspacePurchased: boolean; orders: ServiceOrder[] };
  const run = requestedRunId ? readPlanningRun(requestedRunId) : readActivePlanningRun();
  const records = run ? applicationState.records.filter((record) => record.planningRunId === run.id) : [];
  const selectedIds = run ? readApplicationSelection(run.id) : [];
  const workspacePurchased = applicationState.workspacePurchased;
  const paidOrders = applicationState.orders.filter((order) => order.status === "paid");
  const latestPaidOrder = paidOrders[paidOrders.length - 1];
  const selected = records.map((record) => recommendations.find((school) => school.id === record.schoolRecommendationId)).filter(Boolean) as typeof recommendations;
  const primaryTask = getAtlasPrimaryTask({ applicationRecords: records, selectedSchoolIds: selectedIds, workspacePurchased, journeyNodes: [] });
  const state: ApplicationHomeState = records.length ? "school_confirmed" : "report_ready";
  const copy = applicationStateCopy[state];
  const awaitingWorkspace = primaryTask.id === "choose-application-service";
  const service = getApplicationServiceRecommendation({ confirmedApplications: records, purchasedServices: paidOrders.length > 0, consultationPurchased: paidOrders.some((order) => order.serviceType === "advisor_consultation") });

  if (!run) return <DashboardShell><div className="mx-auto max-w-xl rounded-[24px] border border-[#e7d0c7] bg-[#fffaf3] p-7 text-center"><h1 className="font-editorial text-4xl font-semibold">没有找到本次申请规划。</h1><Link href="/planner" className="mt-6 inline-flex rounded-full bg-[#2f2924] px-6 py-3 text-sm text-white">重新开始免费规划</Link></div></DashboardShell>;

  const intakeLabel = `${run.profile.targetIntake.year} ${run.profile.targetIntake.term === "spring" ? "春季" : run.profile.targetIntake.term === "summer" ? "夏季" : "秋季"}`;
  const recommendationsHref = `/applications/recommendations?runId=${encodeURIComponent(run.id)}`;
  return <DashboardShell><div className="space-y-6">
    <header><nav aria-label="面包屑" className="mb-4 flex items-center gap-2 text-xs text-[#8f847a]"><Link href="/dashboard" className="hover:text-[#2f2924]">我的 Atlas</Link><span>/</span><span className="text-[#4a3d34]">我的申请</span></nav><p className="text-xs uppercase tracking-[0.28em] text-[#9a8b7c]">申请规划</p><h1 className="mt-2 font-editorial text-5xl font-semibold text-[#2f2924] md:text-6xl">我的申请</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#6f6256]">Atlas 把学校确认、材料准备和正式申请安排在同一条清晰路径上。</p></header>
    <Card className="p-5 md:p-7"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-xs uppercase tracking-[0.24em] text-[#9a8b7c]">申请计划概览</p><h2 className="mt-3 font-editorial text-4xl font-semibold text-[#2f2924]">{intakeLabel}入学</h2><div className="mt-5 grid gap-4 text-sm text-[#5d5148] sm:grid-cols-3"><Info label="目标国家" value={run.profile.targetCountries.join("、") || "未设置"} /><Info label="目标方向" value={run.profile.targetSubjects.join("、") || "未设置"} /><Info label="预算" value={run.profile.budgetMax ? `£${run.profile.budgetMin?.toLocaleString() ?? "0"}–£${run.profile.budgetMax.toLocaleString()}` : "未设置"} /></div></div><Link href={recommendationsHref} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#2f2924] px-5 py-3 text-sm font-medium text-[#fffaf3]">查看推荐学校 <ArrowRight size={16} /></Link></div></Card>
    <Card className="border-2 border-[#2f2924] p-5 md:p-7"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><p className="text-xs uppercase tracking-[0.24em] text-[#9a8b7c]">当前最需要完成</p>{primaryTask.schoolName ? <p className="mt-3 text-sm font-medium text-[#8f847a]">{primaryTask.schoolName} · {primaryTask.programName}</p> : null}<h2 className="mt-2 font-editorial text-4xl font-semibold text-[#2f2924]">{primaryTask.title}</h2><p className="mt-3 max-w-2xl text-base leading-7 text-[#5d5148]">{primaryTask.description}</p>{primaryTask.deadline ? <p className="mt-3 text-sm text-[#8f847a]">截止日期：{primaryTask.deadline}</p> : null}</div><span className="rounded-full border border-[#c9dbc5] bg-[#e7ece7] px-3 py-1 text-xs font-medium text-[#4f6d54]">{awaitingWorkspace ? "等待确认" : "现在可以处理"}</span></div><div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-[#f7f0e8] p-4"><p className="text-xs uppercase tracking-[0.18em] text-[#9a8b7c]">Atlas 已准备</p><ul className="mt-3 space-y-2 text-sm text-[#4a3d34]">{(primaryTask.atlasPreparedItems ?? copy.prepared).map((item) => <li key={item} className="flex gap-2"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-[#6f856a]" />{item}</li>)}</ul></div><div className="rounded-2xl bg-[#fffaf3] p-4"><p className="text-xs uppercase tracking-[0.18em] text-[#9a8b7c]">下一步</p><p className="mt-3 text-sm leading-6 text-[#4a3d34]">{primaryTask.userRequiredItems?.length ? `还需处理：${primaryTask.userRequiredItems.join("、")}` : primaryTask.description}</p><Link href={primaryTask.actionHref} className="mt-4 inline-flex items-center gap-2 text-sm font-medium text-[#2f2924] underline decoration-[#c8a96b] underline-offset-4">{primaryTask.actionLabel} <ArrowRight size={15} /></Link></div></div></Card>
    {latestPaidOrder ? <PaidServiceStatus order={latestPaidOrder} /> : null}
    <section><div className="mb-4"><p className="text-xs uppercase tracking-[0.24em] text-[#9a8b7c]">已确认的申请学校</p><h2 className="mt-2 font-editorial text-3xl font-semibold text-[#2f2924]">我的申请学校</h2></div>{selected.length ? <div className="grid gap-4 md:grid-cols-2">{selected.map((school) => <SelectedSchool key={school.id} school={school} record={records.find((record) => record.schoolRecommendationId === school.id)} />)}</div> : <Card className="p-7 text-center"><h3 className="font-editorial text-3xl font-semibold text-[#2f2924]">尚未确认申请学校</h3><p className="mt-3 text-sm leading-6 text-[#6f6256]">请先查看本次规划生成的推荐学校，并确认准备申请的学校。</p><Link href={recommendationsHref} className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#2f2924] px-5 py-3 text-sm text-white">查看推荐学校 <ArrowRight size={15} /></Link></Card>}</section>
    <ServiceRecommendation service={service} hasConfirmed={records.length > 0} />
    <section><div className="mb-4"><p className="text-xs uppercase tracking-[0.24em] text-[#9a8b7c]">Atlas 已完成的准备</p><h2 className="mt-2 font-editorial text-3xl font-semibold text-[#2f2924]">Atlas 已为你准备</h2></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{["已筛选 8 所学校", "已整理学校申请要求", "已生成申请时间安排", "已标记可复用材料", "已准备个人陈述写作重点"].map((item) => <div key={item} className="rounded-2xl bg-[#f7f0e8] p-4 text-sm text-[#4a3d34]"><FileCheck2 size={17} className="text-[#8ea08b]" /><p className="mt-3">{item}</p></div>)}</div></section>
    <section className="border-t border-[#e8dfd3] pt-5"><div className="flex items-center gap-2"><CalendarDays size={17} className="text-[#8ea08b]" /><h2 className="text-sm font-semibold text-[#2f2924]">近期重要日期</h2></div><div className="mt-3 grid gap-2 text-sm text-[#5d5148] md:grid-cols-3"><DateItem date="7 月 18 日" label="Atlas 建议完成：确认学校名单" /><DateItem date="7 月 20 日" label="Atlas 建议完成：材料检查" /><DateItem date="2027 年 1 月 31 日" label="官方截止日期：University of Leeds" /></div></section>
  </div></DashboardShell>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-[#9a8b7c]">{label}</p><p className="mt-1 font-medium text-[#2f2924]">{value}</p></div>; }
function DateItem({ date, label }: { date: string; label: string }) { return <div className="rounded-2xl bg-[#f7f0e8] p-4"><p className="font-semibold text-[#2f2924]">{date}</p><p className="mt-1 leading-6">{label}</p></div>; }
function SelectedSchool({ school, record }: { school: (typeof recommendations)[number]; record?: ApplicationRecord }) {
  const purchased = record?.serviceType === "single_school";
  const status = purchased ? "已购买代递交服务" : record ? "已确认申请" : "已选择";
  return <Card className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-[#8f847a]">{school.country} · {school.city}</p><h3 className="mt-1 text-lg font-semibold text-[#2f2924]">{school.universityName}</h3><p className="mt-1 text-sm text-[#6f6256]">{school.programName}</p></div><span className="rounded-full border border-[#c9dbc5] bg-[#e7ece7] px-3 py-1 text-xs text-[#4f6d54]">{status}</span></div><div className="mt-5 grid gap-2 text-sm text-[#5d5148]"><p>材料已检测到 {record?.detectedMaterialCount ?? school.materialsReady}/{record?.totalMaterials ?? school.materialsTotal} 项</p>{record ? <p>申请进度：{record.applicationProgress}% · 下一步：{record.nextAction}</p> : null}{record?.status === "manual_review" ? <p className="font-medium text-[#4f6d54]">等待 Atlas 审核材料与申请信息</p> : null}</div>{record ? <Link href={`/applications/${record.id}/materials`} className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-[#2f2924] underline underline-offset-4">进入对应工作区 <ArrowRight size={15} /></Link> : null}</Card>;
}

function PaidServiceStatus({ order }: { order: ServiceOrder }) {
  const isSubmission = order.serviceType === "single_school_submission";
  const title = isSubmission ? "Atlas 已开始处理你的学校申请" : order.serviceType === "advisor_consultation" ? "一对一规划服务已确认" : "国家全流程服务已确认";
  const detail = isSubmission ? `已覆盖 ${order.items.length} 所学校，当前正在核对申请材料与基本信息。` : "订单已支付，Atlas 将按照服务方案继续安排下一步。";
  return <Card className="border border-[#bfd2bb] bg-[#f0f5ef] p-5 md:p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><div className="flex items-center gap-2 text-[#4f6d54]"><CheckCircle2 size={18} /><p className="text-xs font-semibold uppercase tracking-[0.18em]">付款成功 · 已自动同步</p></div><h2 className="mt-2 font-editorial text-3xl font-semibold text-[#2f2924]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#5d5148]">{detail}</p></div><Link href="/applications" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-[#2f2924] px-5 py-3 text-sm font-medium text-white">查看服务进度 <ArrowRight size={15} /></Link></div></Card>;
}

function ServiceRecommendation({ service, hasConfirmed }: { service: ReturnType<typeof getApplicationServiceRecommendation>; hasConfirmed: boolean }) {
  if (!hasConfirmed) return null;
  return <Card className="p-5 md:p-6"><p className="text-xs uppercase tracking-[0.24em] text-[#9a8b7c]">申请方式</p><div className="mt-2"><h2 className="font-editorial text-3xl font-semibold text-[#2f2924]">{service.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#6f6256]">{service.description}</p></div><div className="mt-5 grid gap-3 md:grid-cols-3"><Link href="/applications/service-comparison#submission" className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-full bg-[#2f2924] px-5 py-3 text-sm font-medium text-white">选择代申请 <ArrowRight size={15} /></Link><Link href="/applications/service-comparison#advisor" className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-full border border-[#2f2924] px-5 py-3 text-sm font-medium text-[#2f2924]">预约一对一规划 <ArrowRight size={15} /></Link><Link href="/applications/service-comparison#full-france" className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-full border border-[#d8ccbe] px-5 py-3 text-sm font-medium text-[#4a3d34]">查看法国全流程 <ArrowRight size={15} /></Link></div><div className="mt-4 flex flex-wrap gap-2">{service.details.map((item) => <span key={item} className="rounded-full bg-[#f7f0e8] px-3 py-2 text-xs text-[#5d5148]">{item}</span>)}</div></Card>;
}
