"use client";
import Link from "next/link";
import { useState } from "react";
import { Download, LoaderCircle, Sparkles } from "lucide-react";
import { Card } from "@/components/Card";
import type { SchoolRecommendation } from "@/lib/application-prototype-data";
import { readStudentProfile } from "@/lib/student-profile";
export function MotivationLetterVip({ school, applicationId }: { school: SchoolRecommendation; applicationId: string }) {
  const [vip] = useState(() => typeof window !== "undefined" && window.localStorage.getItem("atlas.vip.subscription.v1") === "active");
  const [letter, setLetter] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function generate() { setLoading(true); setError(""); try { const response = await fetch("/api/motivation-letter", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": `${applicationId}-${Date.now()}` }, body: JSON.stringify({ studentProfile: readStudentProfile(), school: { universityName: school.universityName, programName: school.programName, country: school.country, fit: school.recommendationContent?.personalFit, requirements: school.admissionRequirements } }) }); const result = await response.json() as { letter?: string; error?: string | { message?: string; code?: string } }; if (!response.ok) { const message = typeof result.error === "string" ? result.error : result.error?.message; throw new Error(message ?? "生成失败，请稍后重试"); } if (!result.letter) throw new Error("生成结果为空，请重新尝试"); setLetter(result.letter); } catch (cause) { setError(cause instanceof Error ? cause.message : "生成失败，请稍后重试"); } finally { setLoading(false); } }
  function downloadWord() { const safe = letter.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("\n", "<br>"); const html = `<html><head><meta charset="utf-8"><style>@page{size:A4;margin:2.4cm}body{font-family:Georgia,serif;font-size:11pt;line-height:1.45}</style></head><body>${safe}</body></html>`; const url = URL.createObjectURL(new Blob([html], { type: "application/msword;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${school.universityName}-${school.programName}-motivation-letter.doc`; anchor.click(); URL.revokeObjectURL(url); }
  return <Card className="border border-[#d8ccbe] p-5 md:p-7"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><p className="text-xs uppercase tracking-[0.22em] text-[#9a8b7c]">Atlas VIP · 专属文书</p><h2 className="mt-2 font-editorial text-3xl font-semibold text-[#2f2924]">为这所学校生成动机信</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#6f6256]">结合你的真实背景、课程特点和录取要求，生成不超过一页 A4 的学校专属版本，可编辑并下载 Word。</p></div><span className="shrink-0 whitespace-nowrap rounded-full bg-[#2f2924] px-3 py-1 text-xs text-white">¥29.9 / 月</span></div>{vip ? <div className="mt-5"><button type="button" onClick={generate} disabled={loading} className="inline-flex items-center gap-2 rounded-full bg-[#2f2924] px-5 py-3 text-sm text-white disabled:opacity-60">{loading ? <LoaderCircle size={16} className="animate-spin" /> : <Sparkles size={16} />}{loading ? "正在生成……" : letter ? "重新生成" : "生成专属动机信"}</button>{error ? <p className="mt-3 text-sm text-[#9a6257]">{error}</p> : null}{letter ? <div className="mt-5"><textarea value={letter} onChange={(event) => setLetter(event.target.value)} className="min-h-[420px] w-full rounded-2xl border border-[#d8ccbe] bg-white p-5 text-sm leading-7 text-[#3f352e]" /><button type="button" onClick={downloadWord} className="mt-3 inline-flex items-center gap-2 rounded-full border border-[#2f2924] px-5 py-3 text-sm"><Download size={16} />下载 Word</button></div> : null}</div> : <div className="mt-5 rounded-2xl bg-[#f7f0e8] p-4"><p className="text-sm text-[#5d5148]">订阅后可为每一所已确认学校分别生成和下载专属动机信。</p><Link href={`/checkout/vip?returnTo=${encodeURIComponent(`/applications/${encodeURIComponent(applicationId)}/materials`)}`} className="mt-3 inline-flex rounded-full bg-[#2f2924] px-5 py-3 text-sm text-white">查看 VIP 订阅</Link></div>}</Card>;
}
