"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Plus, Trash2 } from "lucide-react";
import { BackHome } from "@/components/PageShell";
import { createPlanningRun, resetDerivedPlanningState } from "@/lib/planning-store";
import { ENGLISH_TESTS, EducationHistory, FRENCH_TESTS, LanguageTest, LanguageTestType, readStudentProfile, StudentProfile, validateStudentProfile, writeStudentProfile } from "@/lib/student-profile";

const input = "quiet-input mt-1 rounded-xl";
const countries = ["中国", "印度", "英国", "法国", "澳洲", "其他"];
const makeEducation = (): EducationHistory => ({ id: crypto.randomUUID(), country: null, institutionNameZh: null, institutionNameEn: null, degreeLevel: null, degreeName: null, major: null, graduationYear: null, graduationMonth: null, graduationStatus: null, arithmeticAverage: null, weightedAverage: null, officialAverage: null, gpa: null, gradingSystem: null, prerequisiteCourses: [] });
const makeTest = (type: LanguageTestType = "IELTS Academic"): LanguageTest => ({ id: crypto.randomUUID(), language: (FRENCH_TESTS as readonly string[]).includes(type) ? "French" : "English", type, overall: null, listening: null, reading: null, writing: null, speaking: null, level: null, testDate: null });
const num = (value: string) => value === "" ? null : Number(value);

export default function PlannerPage() {
  const router = useRouter();
  const [profile, setProfile] = useState<StudentProfile | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { const saved = readStudentProfile(); setProfile({ ...saved, educationHistory: saved.educationHistory.length ? saved.educationHistory : [makeEducation()] }); }, 0); return () => window.clearTimeout(timer); }, []);
  if (!profile) return <main className="atlas-shell py-8">正在读取你的资料…</main>;
  const updateEducation = (id: string, patch: Partial<EducationHistory>) => setProfile({ ...profile, educationHistory: profile.educationHistory.map((item) => item.id === id ? { ...item, ...patch } : item) });
  const updateTest = (id: string, patch: Partial<LanguageTest>) => setProfile({ ...profile, languageTests: profile.languageTests.map((item) => item.id === id ? { ...item, ...patch } : item) });
  function submit(event: FormEvent) { event.preventDefault(); if (!profile) return; try { const valid = validateStudentProfile(profile); writeStudentProfile(valid); const run = createPlanningRun(valid); resetDerivedPlanningState(run.id); router.push(`/result?runId=${encodeURIComponent(run.id)}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "无法保存资料"); } }
  return <main className="atlas-shell py-8"><BackHome /><form onSubmit={submit} className="mx-auto max-w-5xl space-y-8">
    <header><p className="text-xs uppercase tracking-[.25em] text-[#9a8b7c]">Atlas Free Planner</p><h1 className="mt-2 font-editorial text-5xl font-semibold">填写真实背景</h1><p className="mt-3 text-sm text-[#6f6256]">所有分析、确认与推荐都读取这里的同一份资料；未填写内容会保持为空。</p></header>
    <section className="rounded-[24px] bg-[#fffaf3] p-6"><h2 className="text-xl font-semibold">基本信息与目标</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="姓名"><input className={input} value={profile.name ?? ""} onChange={e => setProfile({ ...profile, name: e.target.value || null })} /></Field><Field label="目标国家（用、分隔）"><input className={input} value={profile.targetCountries.join("、")} onChange={e => setProfile({ ...profile, targetCountries: e.target.value.split(/[、,]/).map(x => x.trim()).filter(Boolean) })} /></Field><Field label="目标专业（用、分隔）"><input className={input} value={profile.targetSubjects.join("、")} onChange={e => setProfile({ ...profile, targetSubjects: e.target.value.split(/[、,]/).map(x => x.trim()).filter(Boolean) })} /></Field><Field label="目标学历层级"><select className={input} value={profile.targetDegreeLevel ?? ""} onChange={e => setProfile({ ...profile, targetDegreeLevel: e.target.value === "本科" || e.target.value === "硕士" || e.target.value === "博士" ? e.target.value : null })}><option value="">待确认</option><option>本科</option><option>硕士</option><option>博士</option></select></Field><Field label="入学年份"><input type="number" className={input} value={profile.targetIntake.year ?? ""} onChange={e => setProfile({ ...profile, targetIntake: { ...profile.targetIntake, year: num(e.target.value) } })} /></Field><Field label="每年最高学费预算"><input type="number" className={input} placeholder="预算未设置" value={profile.maxAnnualTuition ?? ""} onChange={e => setProfile({ ...profile, maxAnnualTuition: num(e.target.value) })} /></Field><Field label="币种"><select className={input} value={profile.tuitionCurrency ?? ""} onChange={e => setProfile({ ...profile, tuitionCurrency: e.target.value || null })}><option value="">待确认</option>{["CNY","GBP","EUR","AUD","USD"].map(x => <option key={x}>{x}</option>)}</select></Field></div><div className="mt-4"><span className="text-sm text-[#6f6256]">跨专业范围</span><div className="mt-2 grid gap-2 sm:grid-cols-3">{[["related_only","仅相关专业"],["adjacent","接受相邻专业"],["open","接受明显跨专业"]].map(([value,label]) => <label key={value} className="rounded-xl border border-[#d8ccbe] p-3 text-sm"><input type="radio" className="mr-2" checked={profile.crossDisciplinePreference === value} onChange={() => setProfile({ ...profile, crossDisciplinePreference: value as StudentProfile["crossDisciplinePreference"] })} />{label}</label>)}</div></div></section>
    <section className="space-y-4"><div className="flex justify-between"><h2 className="text-2xl font-semibold">教育经历</h2><button type="button" onClick={() => setProfile({ ...profile, educationHistory: [...profile.educationHistory, makeEducation()] })} className="rounded-full border px-4 py-2 text-sm"><Plus size={15} className="inline" /> 添加</button></div>{profile.educationHistory.map((ed, index) => <div key={ed.id} className="rounded-[24px] bg-[#fffaf3] p-6"><div className="flex justify-between"><strong>教育经历 {index + 1}</strong>{profile.educationHistory.length > 1 && <button type="button" onClick={() => setProfile({ ...profile, educationHistory: profile.educationHistory.filter(x => x.id !== ed.id) })}><Trash2 size={17} /></button>}</div><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="国家/地区"><select className={input} value={ed.country ?? ""} onChange={e => updateEducation(ed.id,{ country:e.target.value || null })}><option value="">待确认</option>{countries.map(x => <option key={x}>{x}</option>)}</select></Field><Field label="学校中文名"><input className={input} value={ed.institutionNameZh ?? ""} onChange={e => updateEducation(ed.id,{ institutionNameZh:e.target.value || null })} /></Field><Field label="学校英文名"><input className={input} value={ed.institutionNameEn ?? ""} onChange={e => updateEducation(ed.id,{ institutionNameEn:e.target.value || null })} /></Field><Field label="学历层级"><input className={input} value={ed.degreeLevel ?? ""} onChange={e => updateEducation(ed.id,{ degreeLevel:e.target.value || null })} /></Field><Field label="学位名称"><input className={input} value={ed.degreeName ?? ""} onChange={e => updateEducation(ed.id,{ degreeName:e.target.value || null })} /></Field><Field label="专业"><input className={input} value={ed.major ?? ""} onChange={e => updateEducation(ed.id,{ major:e.target.value || null })} /></Field><Score label="算术平均分" value={ed.arithmeticAverage} onChange={v => updateEducation(ed.id,{ arithmeticAverage:v })} /><Score label="加权平均分" value={ed.weightedAverage} onChange={v => updateEducation(ed.id,{ weightedAverage:v })} /><Score label="成绩单官方均分" value={ed.officialAverage} onChange={v => updateEducation(ed.id,{ officialAverage:v })} /><Field label="先修课程（用、分隔）"><input className={input} value={ed.prerequisiteCourses.join("、")} onChange={e => updateEducation(ed.id,{ prerequisiteCourses:e.target.value.split(/[、,]/).map(x=>x.trim()).filter(Boolean) })} /></Field></div><p className="mt-4 rounded-xl bg-[#f7f0e8] p-3 text-xs leading-5 text-[#6f6256]">算术平均分：各门成绩等权；加权平均分：按学分加权；成绩单官方均分：学校在正式成绩单上明确给出的均分。Atlas 优先采用官方口径及目标院校规则，不会自动挑最高分。</p></div>)}</section>
    <section className="space-y-4"><div className="flex justify-between"><h2 className="text-2xl font-semibold">语言成绩</h2><button type="button" onClick={() => setProfile({ ...profile, languageTests: [...profile.languageTests, makeTest()] })} className="rounded-full border px-4 py-2 text-sm"><Plus size={15} className="inline" /> 添加</button></div>{!profile.languageTests.length && <p className="rounded-xl bg-[#f7f0e8] p-4 text-sm">未提供/待确认。可同时添加英语和法语考试。</p>}{profile.languageTests.map(test => <div key={test.id} className="rounded-[24px] bg-[#fffaf3] p-6"><div className="flex justify-between"><strong>{test.language === "English" ? "英语" : "法语"}</strong><button type="button" onClick={() => setProfile({ ...profile, languageTests: profile.languageTests.filter(x => x.id !== test.id) })}><Trash2 size={17} /></button></div><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="考试类型"><select className={input} value={test.type} onChange={e => { const type=e.target.value as LanguageTestType; updateTest(test.id,{type,language:(FRENCH_TESTS as readonly string[]).includes(type)?"French":"English"}); }}>{[...ENGLISH_TESTS,...FRENCH_TESTS].map(x => <option key={x}>{x}</option>)}</select></Field>{["DELF","DALF"].includes(test.type) ? <Field label="CEFR 等级"><input className={input} placeholder="如 B2 / C1" value={test.level ?? ""} onChange={e=>updateTest(test.id,{level:e.target.value||null})}/></Field> : <Score label="总分" value={test.overall} onChange={v=>updateTest(test.id,{overall:v})}/>} {! ["DELF","DALF","Duolingo English Test"].includes(test.type) && ["listening","reading","writing","speaking"].map(k => <Score key={k} label={{listening:"听力",reading:"阅读",writing:"写作",speaking:"口语"}[k as "listening"]} value={test[k as keyof LanguageTest] as number|null} onChange={v=>updateTest(test.id,{[k]:v})}/>) }<Field label="考试日期"><input type="date" className={input} value={test.testDate ?? ""} onChange={e=>updateTest(test.id,{testDate:e.target.value||null})}/></Field></div></div>)}</section>
    {error && <p className="text-sm text-red-700">{error}</p>}<button className="w-full rounded-full bg-[#2f2924] px-6 py-4 text-white">保存统一资料并重新计算推荐</button>
  </form></main>;
}
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="text-sm text-[#6f6256]"><span>{label}</span>{children}</label>; }
function Score({label,value,onChange}:{label:string;value:number|null;onChange:(value:number|null)=>void}) { return <Field label={label}><input type="number" step="0.1" className={input} value={value ?? ""} onChange={e=>onChange(num(e.target.value))}/></Field>; }

